// SPDX-License-Identifier: GPL-3.0-only
// © 2026 Patrick JAILLET — RomTranslator

// <auto-generated>
// Ce fichier est généré à partir de Strings.resx : ne pas modifier directement.
// </auto-generated>

using System.Globalization;
using System.Resources;

namespace RomTranslator.Core.Localization;

/// <summary>Chaînes localisées de l'interface (voir Strings.resx / Strings.en.resx).</summary>
public static class Strings
{
    private static readonly ResourceManager _resourceManager = new("RomTranslator.Core.Localization.Strings", typeof(Strings).Assembly);

    /// <summary>Chaîne localisée « Menu_File ».</summary>
    public static string Menu_File => _resourceManager.GetString("Menu_File", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_NewProject ».</summary>
    public static string Menu_File_NewProject => _resourceManager.GetString("Menu_File_NewProject", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_NewProject_ToolTip ».</summary>
    public static string Menu_File_NewProject_ToolTip => _resourceManager.GetString("Menu_File_NewProject_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_OpenProject ».</summary>
    public static string Menu_File_OpenProject => _resourceManager.GetString("Menu_File_OpenProject", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_OpenProject_ToolTip ».</summary>
    public static string Menu_File_OpenProject_ToolTip => _resourceManager.GetString("Menu_File_OpenProject_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_SaveProject ».</summary>
    public static string Menu_File_SaveProject => _resourceManager.GetString("Menu_File_SaveProject", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_SaveProject_ToolTip ».</summary>
    public static string Menu_File_SaveProject_ToolTip => _resourceManager.GetString("Menu_File_SaveProject_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_ExportProject ».</summary>
    public static string Menu_File_ExportProject => _resourceManager.GetString("Menu_File_ExportProject", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_ExportProject_ToolTip ».</summary>
    public static string Menu_File_ExportProject_ToolTip => _resourceManager.GetString("Menu_File_ExportProject_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_Exit ».</summary>
    public static string Menu_File_Exit => _resourceManager.GetString("Menu_File_Exit", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_File_Exit_ToolTip ».</summary>
    public static string Menu_File_Exit_ToolTip => _resourceManager.GetString("Menu_File_Exit_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Edit ».</summary>
    public static string Menu_Edit => _resourceManager.GetString("Menu_Edit", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Edit_Undo ».</summary>
    public static string Menu_Edit_Undo => _resourceManager.GetString("Menu_Edit_Undo", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Edit_Undo_ToolTip ».</summary>
    public static string Menu_Edit_Undo_ToolTip => _resourceManager.GetString("Menu_Edit_Undo_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Edit_Redo ».</summary>
    public static string Menu_Edit_Redo => _resourceManager.GetString("Menu_Edit_Redo", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Edit_Redo_ToolTip ».</summary>
    public static string Menu_Edit_Redo_ToolTip => _resourceManager.GetString("Menu_Edit_Redo_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Tools ».</summary>
    public static string Menu_Tools => _resourceManager.GetString("Menu_Tools", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Tools_Settings ».</summary>
    public static string Menu_Tools_Settings => _resourceManager.GetString("Menu_Tools_Settings", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Tools_Settings_ToolTip ».</summary>
    public static string Menu_Tools_Settings_ToolTip => _resourceManager.GetString("Menu_Tools_Settings_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help ».</summary>
    public static string Menu_Help => _resourceManager.GetString("Menu_Help", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_Online ».</summary>
    public static string Menu_Help_Online => _resourceManager.GetString("Menu_Help_Online", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_Online_ToolTip ».</summary>
    public static string Menu_Help_Online_ToolTip => _resourceManager.GetString("Menu_Help_Online_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_Repository ».</summary>
    public static string Menu_Help_Repository => _resourceManager.GetString("Menu_Help_Repository", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_Repository_ToolTip ».</summary>
    public static string Menu_Help_Repository_ToolTip => _resourceManager.GetString("Menu_Help_Repository_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_Releases ».</summary>
    public static string Menu_Help_Releases => _resourceManager.GetString("Menu_Help_Releases", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_Releases_ToolTip ».</summary>
    public static string Menu_Help_Releases_ToolTip => _resourceManager.GetString("Menu_Help_Releases_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_Contact ».</summary>
    public static string Menu_Help_Contact => _resourceManager.GetString("Menu_Help_Contact", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_Contact_ToolTip ».</summary>
    public static string Menu_Help_Contact_ToolTip => _resourceManager.GetString("Menu_Help_Contact_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_About ».</summary>
    public static string Menu_Help_About => _resourceManager.GetString("Menu_Help_About", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Menu_Help_About_ToolTip ».</summary>
    public static string Menu_Help_About_ToolTip => _resourceManager.GetString("Menu_Help_About_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Link_Website ».</summary>
    public static string Link_Website => _resourceManager.GetString("Link_Website", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Link_Website_Description ».</summary>
    public static string Link_Website_Description => _resourceManager.GetString("Link_Website_Description", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Link_Repository_Description ».</summary>
    public static string Link_Repository_Description => _resourceManager.GetString("Link_Repository_Description", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Link_Releases_Description ».</summary>
    public static string Link_Releases_Description => _resourceManager.GetString("Link_Releases_Description", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Link_Contact_Description ».</summary>
    public static string Link_Contact_Description => _resourceManager.GetString("Link_Contact_Description", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Link_Open ».</summary>
    public static string Link_Open => _resourceManager.GetString("Link_Open", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Tab_Home ».</summary>
    public static string Tab_Home => _resourceManager.GetString("Tab_Home", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « StatusBar_Ready ».</summary>
    public static string StatusBar_Ready => _resourceManager.GetString("StatusBar_Ready", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « StatusBar_LinkOpenFailed ».</summary>
    public static string StatusBar_LinkOpenFailed => _resourceManager.GetString("StatusBar_LinkOpenFailed", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « StatusBar_LanguageToolTip ».</summary>
    public static string StatusBar_LanguageToolTip => _resourceManager.GetString("StatusBar_LanguageToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Home_Welcome ».</summary>
    public static string Home_Welcome => _resourceManager.GetString("Home_Welcome", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Home_Description ».</summary>
    public static string Home_Description => _resourceManager.GetString("Home_Description", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Home_VersionPrefix ».</summary>
    public static string Home_VersionPrefix => _resourceManager.GetString("Home_VersionPrefix", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Home_OneTabPerConsole_Title ».</summary>
    public static string Home_OneTabPerConsole_Title => _resourceManager.GetString("Home_OneTabPerConsole_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Home_OneTabPerConsole_Description ».</summary>
    public static string Home_OneTabPerConsole_Description => _resourceManager.GetString("Home_OneTabPerConsole_Description", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Home_UsefulLinks ».</summary>
    public static string Home_UsefulLinks => _resourceManager.GetString("Home_UsefulLinks", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Home_License ».</summary>
    public static string Home_License => _resourceManager.GetString("Home_License", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Startup_StorageNotWritable ».</summary>
    public static string Startup_StorageNotWritable => _resourceManager.GetString("Startup_StorageNotWritable", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Startup_CrashReportSaved ».</summary>
    public static string Startup_CrashReportSaved => _resourceManager.GetString("Startup_CrashReportSaved", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Startup_CrashReportNotSaved ».</summary>
    public static string Startup_CrashReportNotSaved => _resourceManager.GetString("Startup_CrashReportNotSaved", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Startup_UnhandledException ».</summary>
    public static string Startup_UnhandledException => _resourceManager.GetString("Startup_UnhandledException", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Application_Title ».</summary>
    public static string Application_Title => _resourceManager.GetString("Application_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « TranslationStatus_NotTranslated ».</summary>
    public static string TranslationStatus_NotTranslated => _resourceManager.GetString("TranslationStatus_NotTranslated", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « TranslationStatus_InProgress ».</summary>
    public static string TranslationStatus_InProgress => _resourceManager.GetString("TranslationStatus_InProgress", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « TranslationStatus_Translated ».</summary>
    public static string TranslationStatus_Translated => _resourceManager.GetString("TranslationStatus_Translated", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « TranslationStatus_Validated ».</summary>
    public static string TranslationStatus_Validated => _resourceManager.GetString("TranslationStatus_Validated", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_SearchPlaceholder ».</summary>
    public static string Editor_SearchPlaceholder => _resourceManager.GetString("Editor_SearchPlaceholder", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_FilterAll ».</summary>
    public static string Editor_FilterAll => _resourceManager.GetString("Editor_FilterAll", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_FilterExceedsLimit ».</summary>
    public static string Editor_FilterExceedsLimit => _resourceManager.GetString("Editor_FilterExceedsLimit", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_SourceTextLabel ».</summary>
    public static string Editor_SourceTextLabel => _resourceManager.GetString("Editor_SourceTextLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_TranslatedTextLabel ».</summary>
    public static string Editor_TranslatedTextLabel => _resourceManager.GetString("Editor_TranslatedTextLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_ContextLabel ».</summary>
    public static string Editor_ContextLabel => _resourceManager.GetString("Editor_ContextLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_StatusLabel ».</summary>
    public static string Editor_StatusLabel => _resourceManager.GetString("Editor_StatusLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_OffsetLabel ».</summary>
    public static string Editor_OffsetLabel => _resourceManager.GetString("Editor_OffsetLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_OccurrenceCountLabel ».</summary>
    public static string Editor_OccurrenceCountLabel => _resourceManager.GetString("Editor_OccurrenceCountLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_LengthLimitLabel ».</summary>
    public static string Editor_LengthLimitLabel => _resourceManager.GetString("Editor_LengthLimitLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_LengthLimitExceeded ».</summary>
    public static string Editor_LengthLimitExceeded => _resourceManager.GetString("Editor_LengthLimitExceeded", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_ProgressSummary ».</summary>
    public static string Editor_ProgressSummary => _resourceManager.GetString("Editor_ProgressSummary", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_NoSelection ».</summary>
    public static string Editor_NoSelection => _resourceManager.GetString("Editor_NoSelection", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_NoResults ».</summary>
    public static string Editor_NoResults => _resourceManager.GetString("Editor_NoResults", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_Undo_ToolTip ».</summary>
    public static string Editor_Undo_ToolTip => _resourceManager.GetString("Editor_Undo_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_Redo_ToolTip ».</summary>
    public static string Editor_Redo_ToolTip => _resourceManager.GetString("Editor_Redo_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_OpenFindReplace_ToolTip ».</summary>
    public static string Editor_OpenFindReplace_ToolTip => _resourceManager.GetString("Editor_OpenFindReplace_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_CharacterTablePreviewLabel ».</summary>
    public static string Editor_CharacterTablePreviewLabel => _resourceManager.GetString("Editor_CharacterTablePreviewLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_CharacterTablePreview_UnsupportedCharacter ».</summary>
    public static string Editor_CharacterTablePreview_UnsupportedCharacter => _resourceManager.GetString("Editor_CharacterTablePreview_UnsupportedCharacter", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Editor_OpenGlossary_ToolTip ».</summary>
    public static string Editor_OpenGlossary_ToolTip => _resourceManager.GetString("Editor_OpenGlossary_ToolTip", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « FindReplace_Title ».</summary>
    public static string FindReplace_Title => _resourceManager.GetString("FindReplace_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « FindReplace_SearchLabel ».</summary>
    public static string FindReplace_SearchLabel => _resourceManager.GetString("FindReplace_SearchLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « FindReplace_ReplacementLabel ».</summary>
    public static string FindReplace_ReplacementLabel => _resourceManager.GetString("FindReplace_ReplacementLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « FindReplace_MatchCount ».</summary>
    public static string FindReplace_MatchCount => _resourceManager.GetString("FindReplace_MatchCount", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « FindReplace_ReplaceAllButton ».</summary>
    public static string FindReplace_ReplaceAllButton => _resourceManager.GetString("FindReplace_ReplaceAllButton", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « FindReplace_NoMatch ».</summary>
    public static string FindReplace_NoMatch => _resourceManager.GetString("FindReplace_NoMatch", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « FindReplace_ReplacedCount ».</summary>
    public static string FindReplace_ReplacedCount => _resourceManager.GetString("FindReplace_ReplacedCount", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « FindReplace_CloseButton ».</summary>
    public static string FindReplace_CloseButton => _resourceManager.GetString("FindReplace_CloseButton", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_Title ».</summary>
    public static string Glossary_Title => _resourceManager.GetString("Glossary_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_SourceTermLabel ».</summary>
    public static string Glossary_SourceTermLabel => _resourceManager.GetString("Glossary_SourceTermLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_TargetTermLabel ».</summary>
    public static string Glossary_TargetTermLabel => _resourceManager.GetString("Glossary_TargetTermLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_NoteLabel ».</summary>
    public static string Glossary_NoteLabel => _resourceManager.GetString("Glossary_NoteLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_AddButton ».</summary>
    public static string Glossary_AddButton => _resourceManager.GetString("Glossary_AddButton", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_RemoveButton ».</summary>
    public static string Glossary_RemoveButton => _resourceManager.GetString("Glossary_RemoveButton", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_NewTermWatermark ».</summary>
    public static string Glossary_NewTermWatermark => _resourceManager.GetString("Glossary_NewTermWatermark", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_NoEntries ».</summary>
    public static string Glossary_NoEntries => _resourceManager.GetString("Glossary_NoEntries", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_InconsistenciesHeader ».</summary>
    public static string Glossary_InconsistenciesHeader => _resourceManager.GetString("Glossary_InconsistenciesHeader", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_InconsistencyMessage ».</summary>
    public static string Glossary_InconsistencyMessage => _resourceManager.GetString("Glossary_InconsistencyMessage", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Glossary_CloseButton ».</summary>
    public static string Glossary_CloseButton => _resourceManager.GetString("Glossary_CloseButton", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « About_Title ».</summary>
    public static string About_Title => _resourceManager.GetString("About_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « About_Close ».</summary>
    public static string About_Close => _resourceManager.GetString("About_Close", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_Title ».</summary>
    public static string Settings_Title => _resourceManager.GetString("Settings_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_LanguageSection ».</summary>
    public static string Settings_LanguageSection => _resourceManager.GetString("Settings_LanguageSection", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_LanguageLabel ».</summary>
    public static string Settings_LanguageLabel => _resourceManager.GetString("Settings_LanguageLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_LanguageSystem ».</summary>
    public static string Settings_LanguageSystem => _resourceManager.GetString("Settings_LanguageSystem", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_LanguageFrench ».</summary>
    public static string Settings_LanguageFrench => _resourceManager.GetString("Settings_LanguageFrench", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_LanguageEnglish ».</summary>
    public static string Settings_LanguageEnglish => _resourceManager.GetString("Settings_LanguageEnglish", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_LanguageRestartNotice ».</summary>
    public static string Settings_LanguageRestartNotice => _resourceManager.GetString("Settings_LanguageRestartNotice", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_ThemeSection ».</summary>
    public static string Settings_ThemeSection => _resourceManager.GetString("Settings_ThemeSection", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_ThemeLightOnly ».</summary>
    public static string Settings_ThemeLightOnly => _resourceManager.GetString("Settings_ThemeLightOnly", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_FoldersSection ».</summary>
    public static string Settings_FoldersSection => _resourceManager.GetString("Settings_FoldersSection", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_ConfigFolderLabel ».</summary>
    public static string Settings_ConfigFolderLabel => _resourceManager.GetString("Settings_ConfigFolderLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_ProjectsFolderLabel ».</summary>
    public static string Settings_ProjectsFolderLabel => _resourceManager.GetString("Settings_ProjectsFolderLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_LogsFolderLabel ».</summary>
    public static string Settings_LogsFolderLabel => _resourceManager.GetString("Settings_LogsFolderLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_OpenFolder ».</summary>
    public static string Settings_OpenFolder => _resourceManager.GetString("Settings_OpenFolder", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_Save ».</summary>
    public static string Settings_Save => _resourceManager.GetString("Settings_Save", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Settings_Cancel ».</summary>
    public static string Settings_Cancel => _resourceManager.GetString("Settings_Cancel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « HexViewer_Title ».</summary>
    public static string HexViewer_Title => _resourceManager.GetString("HexViewer_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « HexViewer_PageIndicator ».</summary>
    public static string HexViewer_PageIndicator => _resourceManager.GetString("HexViewer_PageIndicator", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « HexViewer_Previous ».</summary>
    public static string HexViewer_Previous => _resourceManager.GetString("HexViewer_Previous", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « HexViewer_Next ».</summary>
    public static string HexViewer_Next => _resourceManager.GetString("HexViewer_Next", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « HexViewer_FileSizeLabel ».</summary>
    public static string HexViewer_FileSizeLabel => _resourceManager.GetString("HexViewer_FileSizeLabel", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_Title ».</summary>
    public static string Diff_Title => _resourceManager.GetString("Diff_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_Summary ».</summary>
    public static string Diff_Summary => _resourceManager.GetString("Diff_Summary", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_Identical ».</summary>
    public static string Diff_Identical => _resourceManager.GetString("Diff_Identical", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_OffsetColumn ».</summary>
    public static string Diff_OffsetColumn => _resourceManager.GetString("Diff_OffsetColumn", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_LengthColumn ».</summary>
    public static string Diff_LengthColumn => _resourceManager.GetString("Diff_LengthColumn", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_OriginalColumn ».</summary>
    public static string Diff_OriginalColumn => _resourceManager.GetString("Diff_OriginalColumn", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_ModifiedColumn ».</summary>
    public static string Diff_ModifiedColumn => _resourceManager.GetString("Diff_ModifiedColumn", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_CreateIpsPatch ».</summary>
    public static string Diff_CreateIpsPatch => _resourceManager.GetString("Diff_CreateIpsPatch", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_IpsLimitExceeded ».</summary>
    public static string Diff_IpsLimitExceeded => _resourceManager.GetString("Diff_IpsLimitExceeded", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Diff_IpsPatchCreated ».</summary>
    public static string Diff_IpsPatchCreated => _resourceManager.GetString("Diff_IpsPatchCreated", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_CueFileHasNoTrack ».</summary>
    public static string Saturn_Error_CueFileHasNoTrack => _resourceManager.GetString("Saturn_Error_CueFileHasNoTrack", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_CueTrackBeforeFile ».</summary>
    public static string Saturn_Error_CueTrackBeforeFile => _resourceManager.GetString("Saturn_Error_CueTrackBeforeFile", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_CueMalformedTrackLine ».</summary>
    public static string Saturn_Error_CueMalformedTrackLine => _resourceManager.GetString("Saturn_Error_CueMalformedTrackLine", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_CueUnsupportedTrackMode ».</summary>
    public static string Saturn_Error_CueUnsupportedTrackMode => _resourceManager.GetString("Saturn_Error_CueUnsupportedTrackMode", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_CueMissingFileName ».</summary>
    public static string Saturn_Error_CueMissingFileName => _resourceManager.GetString("Saturn_Error_CueMissingFileName", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_NoDataTrack ».</summary>
    public static string Saturn_Error_NoDataTrack => _resourceManager.GetString("Saturn_Error_NoDataTrack", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_MissingHardwareId ».</summary>
    public static string Saturn_Error_MissingHardwareId => _resourceManager.GetString("Saturn_Error_MissingHardwareId", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_HeaderTooShort ».</summary>
    public static string Saturn_Error_HeaderTooShort => _resourceManager.GetString("Saturn_Error_HeaderTooShort", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_VolumeDescriptorNotFound ».</summary>
    public static string Saturn_Error_VolumeDescriptorNotFound => _resourceManager.GetString("Saturn_Error_VolumeDescriptorNotFound", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Validation_TrackFileMissing ».</summary>
    public static string Saturn_Validation_TrackFileMissing => _resourceManager.GetString("Saturn_Validation_TrackFileMissing", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Validation_TruncatedImage ».</summary>
    public static string Saturn_Validation_TruncatedImage => _resourceManager.GetString("Saturn_Validation_TruncatedImage", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Validation_UnreadableIpBin ».</summary>
    public static string Saturn_Validation_UnreadableIpBin => _resourceManager.GetString("Saturn_Validation_UnreadableIpBin", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Validation_DetectedRegion ».</summary>
    public static string Saturn_Validation_DetectedRegion => _resourceManager.GetString("Saturn_Validation_DetectedRegion", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Validation_UnknownRegion ».</summary>
    public static string Saturn_Validation_UnknownRegion => _resourceManager.GetString("Saturn_Validation_UnknownRegion", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_TableMalformedLine ».</summary>
    public static string Saturn_Error_TableMalformedLine => _resourceManager.GetString("Saturn_Error_TableMalformedLine", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Error_TableInvalidHex ».</summary>
    public static string Saturn_Error_TableInvalidHex => _resourceManager.GetString("Saturn_Error_TableInvalidHex", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Table_DuplicateByteSequence ».</summary>
    public static string Saturn_Table_DuplicateByteSequence => _resourceManager.GetString("Saturn_Table_DuplicateByteSequence", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Table_DuplicateText ».</summary>
    public static string Saturn_Table_DuplicateText => _resourceManager.GetString("Saturn_Table_DuplicateText", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Table_UnknownByte ».</summary>
    public static string Saturn_Table_UnknownByte => _resourceManager.GetString("Saturn_Table_UnknownByte", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_Table_UnknownCharacter ».</summary>
    public static string Saturn_Table_UnknownCharacter => _resourceManager.GetString("Saturn_Table_UnknownCharacter", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_Title ».</summary>
    public static string Saturn_CharacterTableEditor_Title => _resourceManager.GetString("Saturn_CharacterTableEditor_Title", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_Add ».</summary>
    public static string Saturn_CharacterTableEditor_Add => _resourceManager.GetString("Saturn_CharacterTableEditor_Add", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_Remove ».</summary>
    public static string Saturn_CharacterTableEditor_Remove => _resourceManager.GetString("Saturn_CharacterTableEditor_Remove", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_Load ».</summary>
    public static string Saturn_CharacterTableEditor_Load => _resourceManager.GetString("Saturn_CharacterTableEditor_Load", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_Save ».</summary>
    public static string Saturn_CharacterTableEditor_Save => _resourceManager.GetString("Saturn_CharacterTableEditor_Save", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_BytesColumn ».</summary>
    public static string Saturn_CharacterTableEditor_BytesColumn => _resourceManager.GetString("Saturn_CharacterTableEditor_BytesColumn", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_TextColumn ».</summary>
    public static string Saturn_CharacterTableEditor_TextColumn => _resourceManager.GetString("Saturn_CharacterTableEditor_TextColumn", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_ValidColumn ».</summary>
    public static string Saturn_CharacterTableEditor_ValidColumn => _resourceManager.GetString("Saturn_CharacterTableEditor_ValidColumn", CultureInfo.CurrentUICulture) ?? string.Empty;

    /// <summary>Chaîne localisée « Saturn_CharacterTableEditor_FileFilter ».</summary>
    public static string Saturn_CharacterTableEditor_FileFilter => _resourceManager.GetString("Saturn_CharacterTableEditor_FileFilter", CultureInfo.CurrentUICulture) ?? string.Empty;

}
